@startuml database
title database

class offdata{
    PK: id INTEGER NOT NULL
    ---
    substitut VARCHAR
    description VARCHAR
    magasin VARCHAR
    lien_off VARCHAR

}

    ' catégorie
    ' nom_aliment

class user_favorites{
    PK: id INTEGER NOT NULL
    FPK: id_offdata INTEGER
}

@enduml