@startuml 02_uc_database
title Diagramme de cas d'utilisation *Database*

package database{
    (Créer la base de donnée) as CREATE
    (Remplir la base de donnée) as FILL
    (Consulter les données) as READ
    (Enregistrer des données) as SET
}

actor OpenFoofFacts <<system>>

FILL -u- OpenFoofFacts

@enduml