@startuml 05_class

class GUI{
    --
    Select_category()
    Select_product()
    Select_substitute()
    Save_substitute()
    Show_substitute()
    Delete_substitute()
}

class DATABASE{
    Categories
    Off_datas
    Substitute
    --
    Create_database()
    Fillin_database()
}

@enduml