@startuml

    class category {
        PK id : int(2)
        --
        name : varchar(255)
    }

    class product {
        PK id : int(2)
        FK id_category
        --
        name : varchar(255)
    }

    class offData {
        PK id : int
        FK id_product
        --
        product-name VARCHAR
        brands : varchar(255)
        quantity : varchar(255)
        stores : varchar(255)
        url : varchar(255)
        user_favorite : boolean

    }

    category "1" *-- "1..*" product
    product "1" *-- "1..*" offData

@enduml