@startuml

    class category {
        PK id : int
        --
        name : varchar(255)
    }

    class product {
        PK id : int
        FK id_category
        --
        product-name varchar(255)
        brands : varchar(255)
        quantity : varchar(255)
        stores : varchar(255)
        url : varchar(255)
        nutrition_grades : varchar(1)
    }

    class substite{
        PK id : int
        --
        FK id_origin
        FK id_substitute
    }

    category "1" -- "1..*" product
    product "2" - "*" substite

@enduml